### ISSUE TITLE
Spelling mistake in user view

### ISSUE THREAD

**Issue by SubGplayz** [WemXPro/admin_theme-default#3]
![image](https://github.com/WemXPro/admin_theme-default/assets/68687751/f3e5860d-f5c3-4aa9-95c9-70dda9df0c86)

"Vissibility" is incorrectly spelt, it should be spelt "Visibility"

**Comment by PadowYT2** [comment]
Wrong repository, the right one is https://github.com/VertisanPRO/pterodactyl
